/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import controller.datarentalcontroller;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frameInputData extends javax.swing.JFrame {

    /**
     * Creates new form frameInputData
     */
    datarentalcontroller dc;
    public frameInputData() {
        initComponents();
        
         Jradiobtn1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jradiobtn1ActionPerformed(evt);
            }
        });

        Jradiobtn2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jradiobtn2ActionPerformed(evt);
            }
        });
        
//        frameTampilData frameTampil = new frameTampilData(); // Buat objek frameTampilData
//        dc = new datarentalcontroller(frameTampil); // Kirimkan objek frameTampilData yang benar
//        dc.isitabel();
         frameInputData frameInput = new frameInputData(); // Buat objek frameTampilData
        dc = new datarentalcontroller(frameInput); // Kirimkan objek frameTampilData yang benar
        dc.isitabel();
//       dc = new datarentalcontroller(this); // Menggunakan "this" sebagai argumen
//        dc.isitabel();
    }

    frameInputData(frameTampilData frameTampil) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        JTxtNamaCustomer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jradiobtn1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JDropKendaraan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JFieldBiayaPerjam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JFieldLamaSewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTxtnoHp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JFieldTotalBiaya = new javax.swing.JTextField();
        inputBtn = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Jradiobtn2 = new javax.swing.JRadioButton();
        hitungbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("STHupo", 0, 36)); // NOI18N
        jLabel1.setText("Form Perentalan Kendaraan");

        JTxtNamaCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtNamaCustomerActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Penyewa :");

        buttonGroup1.add(Jradiobtn1);
        Jradiobtn1.setText("Mobil");
        Jradiobtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jradiobtn1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipe Kendaraan : ");

        jLabel4.setText("Nama Kendaraan :");

        JDropKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~SILAHKAN PILIH~", "Ferrari", "Koenisegg", "Pagani", "Avanza", "Kijang Kotak", " " }));
        JDropKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDropKendaraanActionPerformed(evt);
            }
        });

        jLabel5.setText("Biaya /Jam :");

        JFieldBiayaPerjam.setEditable(false);
        JFieldBiayaPerjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFieldBiayaPerjamActionPerformed(evt);
            }
        });

        jLabel6.setText("Lama Waktu Sewa (Jam) :");

        JFieldLamaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFieldLamaSewaActionPerformed(evt);
            }
        });

        jLabel7.setText("No.HP               :");

        JTxtnoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtnoHpActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Biaya :");

        JFieldTotalBiaya.setEditable(false);
        JFieldTotalBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFieldTotalBiayaActionPerformed(evt);
            }
        });

        inputBtn.setText("Input Data Rental");
        inputBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBtnActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Kembali ke Home");

        buttonGroup1.add(Jradiobtn2);
        Jradiobtn2.setText("Motor");
        Jradiobtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jradiobtn2ActionPerformed(evt);
            }
        });

        hitungbtn.setText("Hitung Biaya");
        hitungbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTxtNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTxtnoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(Jradiobtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jradiobtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(222, 222, 222))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(JDropKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(JFieldBiayaPerjam, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                    .addComponent(JFieldLamaSewa)))
                                            .addComponent(inputBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(hitungbtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(JFieldTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTxtNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Jradiobtn1)
                    .addComponent(Jradiobtn2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JDropKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JFieldBiayaPerjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JFieldLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hitungbtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(JFieldTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(inputBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(JTxtnoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addComponent(jToggleButton2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtNamaCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtNamaCustomerActionPerformed
        
    }//GEN-LAST:event_JTxtNamaCustomerActionPerformed

    private void JDropKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDropKendaraanActionPerformed
         int index = JDropKendaraan.getSelectedIndex();

    if (Jradiobtn1.isSelected()) { // Jika yang dipilih adalah mobil
        switch (index) {
//            case 0:
//                JFieldBiayaPerjam.setText("");
//                break;
            case 0:
                JFieldBiayaPerjam.setText("200000"); // Biaya Ferrari
                break;
            case 1:
                JFieldBiayaPerjam.setText("500000"); // Biaya Koenisegg
                break;
            case 2:
                JFieldBiayaPerjam.setText("350000"); // Biaya Pagani
                break;
            case 3:
                JFieldBiayaPerjam.setText("190000"); // Biaya Avanza
                break;
            case 4:
                JFieldBiayaPerjam.setText("90000");  // Biaya Kijang Kotak
                break;
            default:
                break;
        }
    } else if (Jradiobtn2.isSelected()) { // Jika yang dipilih adalah motor
        switch (index) {
//            case 0:
//                JFieldBiayaPerjam.setText("");
//                break;
            case 0:
                JFieldBiayaPerjam.setText("100000"); // Biaya Honda
                break;
            case 1:
                JFieldBiayaPerjam.setText("80000");  // Biaya Yamaha
                break;
            case 2:
                JFieldBiayaPerjam.setText("90000");  // Biaya Suzuki
                break;
            case 3:
                JFieldBiayaPerjam.setText("120000"); // Biaya Kawasaki
                break;
            default:
                break;
        }
    }
    }//GEN-LAST:event_JDropKendaraanActionPerformed

    private void Jradiobtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jradiobtn1ActionPerformed
        // TODO add your handling code here:
         JDropKendaraan.removeAllItems(); // Kosongkan dulu dropdown

        // Tambahkan opsi untuk mobil
        JDropKendaraan.addItem("Ferrari");
        JDropKendaraan.addItem("Koenisegg");
        JDropKendaraan.addItem("Pagani");
        JDropKendaraan.addItem("Avanza");
        JDropKendaraan.addItem("Kijang Kotak");
    }//GEN-LAST:event_Jradiobtn1ActionPerformed

    private void JFieldBiayaPerjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFieldBiayaPerjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFieldBiayaPerjamActionPerformed

    private void JFieldLamaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFieldLamaSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFieldLamaSewaActionPerformed

    private void JTxtnoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtnoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtnoHpActionPerformed

    private void JFieldTotalBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFieldTotalBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFieldTotalBiayaActionPerformed

    private void Jradiobtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jradiobtn2ActionPerformed
        // TODO add your handling code here:
          JDropKendaraan.removeAllItems(); // Kosongkan dulu dropdown

        // Tambahkan opsi untuk motor
        JDropKendaraan.addItem("Honda");
        JDropKendaraan.addItem("Yamaha");
        JDropKendaraan.addItem("Suzuki");
        JDropKendaraan.addItem("Kawasaki");
    }//GEN-LAST:event_Jradiobtn2ActionPerformed

    private void inputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBtnActionPerformed
       // datarentalcontroller dc = new datarentalcontroller(frame2);
      //  dc.insert();
     //   dc.isitabel();
       dc.insert();
    this.dispose(); // Menutup frame input data

    // Membuat objek baru untuk frame tampil data dan menampilkannya
    frameTampilData frameTampil = new frameTampilData();
    frameTampil.setVisible(true);
    frameTampil.setLocationRelativeTo(null);
    }//GEN-LAST:event_inputBtnActionPerformed

    private void hitungbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbtnActionPerformed
        // TODO add your handling code here:
           // Mengambil nilai biaya per jam dari JFieldBiayaPerjam
    String biayaPerJamStr = JFieldBiayaPerjam.getText();
    // Mengambil nilai lama waktu sewa dari JFieldLamaSewa
    String lamaSewaStr = JFieldLamaSewa.getText();

    try {
        // Parsing nilai biaya per jam dan lama waktu sewa menjadi numerik (double)
        double biayaPerJam = Double.parseDouble(biayaPerJamStr);
        int lamaSewa = Integer.parseInt(lamaSewaStr);

        // Menghitung total biaya
        double totalBiaya = biayaPerJam * lamaSewa;

        // Mengatur nilai total biaya ke dalam JFieldTotalBiaya
        JFieldTotalBiaya.setText(String.valueOf(totalBiaya));
    } catch (NumberFormatException e) {
        // Handle jika terjadi error saat parsing
        System.err.println("Error: " + e.getMessage());
        // Atau tambahkan tindakan lain sesuai kebutuhan, misalnya memberi peringatan kepada pengguna
    }
    }//GEN-LAST:event_hitungbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameInputData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JDropKendaraan;
    private javax.swing.JTextField JFieldBiayaPerjam;
    private javax.swing.JTextField JFieldLamaSewa;
    private javax.swing.JTextField JFieldTotalBiaya;
    private javax.swing.JTextField JTxtNamaCustomer;
    private javax.swing.JTextField JTxtnoHp;
    private javax.swing.JRadioButton Jradiobtn1;
    private javax.swing.JRadioButton Jradiobtn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hitungbtn;
    private javax.swing.JToggleButton inputBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getJDropKendaraan() {
        return JDropKendaraan;
    }

    public void setJDropKendaraan(JComboBox<String> JDropKendaraan) {
        this.JDropKendaraan = JDropKendaraan;
    }

    public JTextField getJFieldBiayaPerjam() {
        return JFieldBiayaPerjam;
    }

    public void setJFieldBiayaPerjam(JTextField JFieldBiayaPerjam) {
        this.JFieldBiayaPerjam = JFieldBiayaPerjam;
    }

    public JTextField getJFieldLamaSewa() {
        return JFieldLamaSewa;
    }

    public void setJFieldLamaSewa(JTextField JFieldLamaSewa) {
        this.JFieldLamaSewa = JFieldLamaSewa;
    }

    public JTextField getJFieldTotalBiaya() {
        return JFieldTotalBiaya;
    }

    public void setJFieldTotalBiaya(JTextField JFieldTotalBiaya) {
        this.JFieldTotalBiaya = JFieldTotalBiaya;
    }

    public JTextField getJTxtNamaCustomer() {
        return JTxtNamaCustomer;
    }

    public void setJTxtNamaCustomer(JTextField JTxtNamaCustomer) {
        this.JTxtNamaCustomer = JTxtNamaCustomer;
    }

    public JTextField getJTxtnoHp() {
        return JTxtnoHp;
    }

    public void setJTxtnoHp(JTextField JTxtnoHp) {
        this.JTxtnoHp = JTxtnoHp;
    }

    public JRadioButton getJradiobtn1() {
        return Jradiobtn1;
    }

    public void setJradiobtn1(JRadioButton Jradiobtn1) {
        this.Jradiobtn1 = Jradiobtn1;
    }

    public JRadioButton getJradiobtn2() {
        return Jradiobtn2;
    }

    public void setJradiobtn2(JRadioButton Jradiobtn2) {
        this.Jradiobtn2 = Jradiobtn2;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JToggleButton getjToggleButton2() {
        return jToggleButton2;
    }

    public void setjToggleButton2(JToggleButton jToggleButton2) {
        this.jToggleButton2 = jToggleButton2;
    }

    
}
